### PR TITLE
Use default SSLSocketFactory to solve TrustManager security vulnerability reported by Google Play

### LINKED ISSUE #27: issue with x509trustmanager
class vulnerability
com.rhyme.r_scan.ImageScanHelper$MyX509TrustManager

### PR DESCRIPTION
**Pull request by masewo**
If you try to publish an app that uses this plulgin on Google Play, Google Play will report a security vulnerability because a custom TrustManager is used that overrides methods checkClientTrusted and checkServerTrusted with empty bodies.

To solve this issue we can use the default SSLSocketFactory.

### CODE REVIEW

**Comment by AkoWu101** [comment]
will merge it?

**Comment by AkoWu101** [comment]
Will have this compile error 
```In file included from ios/Pods/ZBarSDK/zbar/qrcode/qrdec.c:19:
 /ios/Pods/gRPC-C++/src/core/lib/iomgr/error.h:22:10: fatal error: 'grpc/support/port_platform.h' file
```

**Review by rhymelph — COMMENTED** [review]
merge

**Comment by rhymelph** [comment]
thx @masewo

**Pull request merged**
